POST  http://localhost:3000/createRegisterBookDiary
Content-Type: application/json

{
    "id_libro_diario": null,
    "id_usuario": 1,
    "id_grupo": 1,
    "id_tipo": 1,
    "id_rubro": 1,
    "id_sub_rubro": 1,
    "id_forma_pago": 1,
    "id_cuenta": 1,
    "fecha_registro": "2024-09-07",
    "descripcion": "Pago proveedor",
    "debe": 0,
    "haber": 1500,
    "gestion": 1,
    "codigo_cuentas": null
}