POST  http://localhost:3000/createRegisterBookDiary
Content-Type: application/json

{
    "id_usuario": 1,
    "id_grupo": 1,
    "id_tipo": 1,
    "id_rubro": 1,
    "id_sub_rubro": 1,
    "id_forma_pago": 1,
    "id_cuenta": 1,
    "fecha_registro": "2024-09-08",
    "descripcion": "Pago proveedor",
    "debe": 1500,
    "haber": 0,
    "gestion": 1,
    "codigo_cuenta": ""
}